In [2]:
#Installing PyTorch and checking the version we are using that
import torch #the purpose of this is to make the torch library available to use for the rest of the code
torch.__version__ #the two long dashes __word__ are called dunder or magic methods which are special methods in Python

'2.5.1'

# Introduction to Tensors

- Fundamental building block of ML
- Represent data in a numerical way
- Could represent an image a tensor shape [3, 224, 224], which would mean [color_channels, height, width]
    - 3 color channels rgb
    - Height = 224 pixels
    - Width = 224 pixels
    - This tensor would have 3 dimensions
- *Read through the torch.Tensor class documentation page!*

## Scalar Tensor

In [3]:

import torch
torch.__version__
#First thing we do is create a scalar 
#A Scalar is a single number and is a 0-dimensional tensor that 

scalar = torch.tensor(7) 
scalar #although its just the number 7, it is the type of torch.Tensor
print(scalar) #this gives tensor(7)

#Check dimensions of the tensor using ndim
scalar.ndim 
print(f"The number of dimensions of the scalar is: {scalar.ndim} dimensions")

#If we want to retrieve the number from the tensor, turn it from type torch.Tensor into a Python int variable 
#Use the item method
number=scalar.item()
print(f"Turning the torch Tensor into a Python int variable: {number}")

tensor(7)
The number of dimensions of the scalar is: 0 dimensions
Turning the torch Tensor into a Python int variable: 7


## Vector Tensor

In [4]:
# Vectors 
# are a single dimensional tensor but can contain many numbers
# Could have [3, 2] to describe [bedrooms, bathrooms] in your house
# You could have [3,2,2] to describe bedrooms bathroom and cars parked
# Vectors are flexible in what they can represent

#Vector
vector = torch.Tensor([7,7]) #Notice one bracket on each side
print(vector) #Notice that this print statement will include the word tensor

#Checking the dimensions of the vector
vector.ndim #There are no () after ndim becauser it is not a method, it is an attribute
print(f"The dimensions of the vector is: {vector.ndim}") 

#The dimension returned here is 1, because it is a 1D tensor
#It is easy to know what the dimension is by looking at the number of brackets on ONE SIDE

#Shape of Vector (how many elements are in the vector)
vector.shape
print(f"The shape of the vector is: {vector.shape}")

tensor([7., 7.])
The dimensions of the vector is: 1
The shape of the vector is: torch.Size([2])


## Matrix Tensor

In [ ]:
#Matrix
#Since this is a 2D tensor, and we are making it a 2x2 shape will return size, make sure you separate the rows with a comma
MATRIX = torch.tensor( [ [7, 8],
                        [9, 10]])
print(f"Matrix Created: {MATRIX}")

#Checking the number of dimensions, should be 2
print(f"The number of dimensions (brackets) of the matrix is: {MATRIX.ndim}")

#When we test the shape of a matrix, instead of number of elements (like vectors), we get number of rows and columns
print(f"The shape of this matrix (rows, cols) is: {MATRIX.shape}")

Matrix Created: tensor([[ 7,  8],
        [ 9, 10]])
The number of dimensions (brackets) of the matrix is: 2
The shape of this matrix (rows, cols) is: torch.Size([2, 2])


## N-Dimensional Tensor

In [5]:
#Tensor
#Generally, Tensors are 3D or more
#Reminder: 0D = Scalar, 1D = Vector, 2D = Matrix

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

print(f"The tensor created is: {TENSOR}")

#Tensors can represent almost anything, for example the one we just created could be in an excel sheet:
#Days of week:      1 2 3
#Steak Sales:       3 6 9
#Almond Milk Sales: 2 4 5

#What will be the number of dimensions (remember, number of square brackets)
print(f"The above tensor has (number of brackets) {TENSOR.ndim} dimensions")

#What will the shape be? Remember, the numbers shown in shape represent # elements in outer to inner (0->nth) dimensions
# This tensor has 1 element in outer dimension (a 3x3 matrix)
# 3 elements in the middle dimension (3 vectors which are the rows)
# 3 elements in the inner dimension (3 numbers in each vector which are the columns)
print(f"The tensor has a shape of: {TENSOR.shape}")

new_tensor = torch.tensor([[[1,1],
                            [1,1],
                            [1,1]]])
print(f"The new tensor is: {new_tensor}")
print(f"The shape of the new tensor is: {new_tensor.shape} which can be though of as 1 3x2 matrix")


The tensor created is: tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
The above tensor has (number of brackets) 3 dimensions
The tensor has a shape of: torch.Size([1, 3, 3])
The new tensor is: tensor([[[1, 1],
         [1, 1],
         [1, 1]]])
The shape of the new tensor is: torch.Size([1, 3, 2]) which can be though of as 1 3x2 matrix


## Summary of Tensors

Scalar: torch.tensor(1)
- Single number
- ndim=0
- scalar.shape returns torch.Size([])
- use scalar.item() to get it from tensor to python var
- v

Vector: torch.tensor([1,1])
- Multiple numbers, has direction
- ndim-1
- vector.shape returns torch.Size([# of items])
- y

Matrix: torch.tensor([[1,1],[1,1]])
- 2 Dimensional array of numbers of nxm
- ndim=2
- matrix.shape return torch.Size([#rows, #columns])

Tensor: torch.tensor([[[1,1],[1,1],[1,1]]])
- n dimensional array of numbers (think matrices with matrices inside)
- ndim=3 (number of brackets!)
- tensor.shape here gives torch.Size([1,3,2])m can think of this as 1 3x2 matrix
    - it has dim of 3 because there is specifically 1 matrix, there could be 2 or 3


# Tensor Initialization
It is very rare to actually create tensors by hand as we did above

## Random Tensors
ML models start out with **large random tensors** of numbers and *adjusts* these random numbers as it works through data to better represent it

You define how model starts (*initialization*), looks at data (*representation*), and updates (*optimization*) random numbers

Let us create some random tensors now

In [6]:
#Creating random tensor of size (3,4)
random_tensor = torch.rand(3,4)
print(f"The random tensor initialized with torch.rand(3,4) is:\n {random_tensor} \nwith a datatype of: {random_tensor.dtype}") 
#Notice that the numbers are between 0 and 1 because we used torch.rand() which is a random number between 0 and 1

print(f"THe tensor has a shape of: {random_tensor.shape} and a dimension of: {random_tensor.ndim}") #ndim=2 because it's a matrix, so here trick is count number of arguments

#The flexibility of torch.rand() is that we can adjust the size to be whatever we want
#Remember that this rand function takes in the SHAPE of the tensor

bigger_random_tensor = torch.rand(2,3,4,2) #Imagine this as a pair of: (3 sets of (4x2 matrices)), which gives ndim of 4 (# of arguments) and shape of 2,3,4,2
print(f"The bigger random tensor is: {bigger_random_tensor} \nwith a shape of: {bigger_random_tensor.shape} and a dimension of: {bigger_random_tensor.ndim}")

The random tensor initialized with torch.rand(3,4) is:
 tensor([[0.5680, 0.3554, 0.2648, 0.6336],
        [0.9397, 0.6918, 0.6551, 0.3318],
        [0.6601, 0.4567, 0.3523, 0.6074]]) 
with a datatype of: torch.float32
THe tensor has a shape of: torch.Size([3, 4]) and a dimension of: 2
The bigger random tensor is: tensor([[[[0.6002, 0.5602],
          [0.3055, 0.7475],
          [0.9063, 0.3638],
          [0.8091, 0.9995]],

         [[0.1936, 0.1750],
          [0.4837, 0.5747],
          [0.4713, 0.1408],
          [0.0995, 0.5007]],

         [[0.7947, 0.5934],
          [0.2074, 0.5156],
          [0.8116, 0.5935],
          [0.3213, 0.3380]]],


        [[[0.4625, 0.8709],
          [0.2010, 0.2471],
          [0.0499, 0.6338],
          [0.0359, 0.3935]],

         [[0.3626, 0.8129],
          [0.3562, 0.3625],
          [0.5605, 0.1850],
          [0.6653, 0.0507]],

         [[0.1822, 0.4924],
          [0.6575, 0.6219],
          [0.4614, 0.3515],
          [0.5467, 0.2246]]]]

### Random Tensor to represent an RGB 224x224 Image
Suppose we want a random tensor in the common image shape of 224x224x3 (height, width, color channels)

In [ ]:
random_image_tensor = torch.rand(224,224,3)
print(f"The Random Image Tensor is: {random_image_tensor} \nwith a shape of: {random_image_tensor.shape} and a dimension of: {random_image_tensor.ndim}")

The Random Image Tensor is: tensor([[[0.4889, 0.2771, 0.2280],
         [0.8962, 0.6210, 0.5955],
         [0.0240, 0.0587, 0.3160],
         ...,
         [0.6887, 0.2782, 0.7014],
         [0.0312, 0.2256, 0.7841],
         [0.6663, 0.2729, 0.0788]],

        [[0.0094, 0.2294, 0.8958],
         [0.6068, 0.0481, 0.1754],
         [0.8739, 0.0670, 0.5417],
         ...,
         [0.9260, 0.1218, 0.0409],
         [0.4629, 0.6014, 0.5497],
         [0.4640, 0.9062, 0.2158]],

        [[0.1015, 0.7591, 0.5533],
         [0.5087, 0.2310, 0.3943],
         [0.2888, 0.6591, 0.5034],
         ...,
         [0.4767, 0.4782, 0.6223],
         [0.5369, 0.0837, 0.7304],
         [0.9434, 0.2738, 0.4600]],

        ...,

        [[0.7764, 0.0730, 0.5117],
         [0.6333, 0.1247, 0.1301],
         [0.0756, 0.4859, 0.1139],
         ...,
         [0.6483, 0.6456, 0.5700],
         [0.3967, 0.2845, 0.2142],
         [0.2725, 0.0059, 0.2231]],

        [[0.7231, 0.7381, 0.4745],
         [0.4478, 0

## Zeros & Ones Tensors
Sometimes, we just want to fill tensors with 0s or 1s specifically

We do this alot with masking, which is when we 0 values so the model knows not to learn them

In [ ]:
#Creating a tensor full of 0s
zeroes = torch.zeros(size=(3,4)) #size is optional, we can just use 3,4
print(zeroes, zeroes.dtype)
zero = torch.zeros(3,4)
print(zero, zeroes.dtype)

#Can do the same for creatin tensors of all ones
ones = torch.ones(3,4)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### arange() Tensors
- If we want a range of numbers such as 1-10 or 0-100, we can use torch.arrange(start, end, step)
- Start: starty of range like 0
- End: end of range like 10 IT WILL NOT INCLUDE THIS NUMBER
    - If we want to include the end number, we can use torch.arange(start, end+1, step)
- Step: Number of steps between each value like 1

In [7]:
#goes from 0 to 9, dont need to write start=0, end=10, step=1
zero_to_ten = torch.arange(start=0, end=11, step=1) 
print(zero_to_ten)

#if we don't specify start, it will start at 0
other = torch.arange(11) 
print(other)

#if we want to get even numbers through 20
evens_thru_20 = torch.arange(0,21,2)
print(evens_thru_20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


### Broadcasting like() Tensors
- Sometimes you might want 1 tensor of a certain type with the same shape as another tensor
- For example, a tensor with all 0s with the same shape as a previous tensor
- You can use another tensor as an input

In [10]:
#Initialize tensor 1 to 21 (ndim=1, shape=(21,))
one_to_21 = torch.arange(1,22)
print(one_to_21, one_to_21.shape)

#Create a tensor of all zeroes with the same shape as one_to_21
twenty_one_zeroes = torch.zeros_like(one_to_21) #You could also write input=one_to_21 in the ()'s to be more specific
print(twenty_one_zeroes, twenty_one_zeroes.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21]) torch.Size([21])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) torch.Size([21])


## DIfferent Tensor Types
- There are many different tensor datatypes in pyTorch, some specific for CPU and others for GPU
    - Generally, if you see torch.cuda anywhere, the tensor is being used for GPU, since Nvidia GPUs use a computing toolkit called CUDA
- The most common data type and generally the default is torch.float32 or torch.float, which is referred to as "32-bit floating point"
    - There is also a 16-bit floating point: torch.float16 or torch.half
    - A 64-bit floating point is torch.float64 or torch.double
    - To confuse things even more, there are also 8, 16, 32, and 64 bit INTEGERS!
    - The reason for all of these is for precision in computing, the amount of detail used to describe a number
    - The higher the precision value (bits), the more detail and hence data used to express a number
    - This all matters in DL because you're making so many operations, the more detail you have to calculate on, the more compute you have to use
    - Lower precision data types are faster but sacrifice some performance on evaluation metrics like accuracy

### 32 & 16-bit Floating Point Tensors

In [11]:
#Tensor Datatypes

#We will implement the dtype parameter now
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                dtype=None, #will default to None anyway, which is torch.float32 
                device=None, #will default to None, which is CPU
                requires_grad=False) #if True, operations performed on the tensor are recorded for grad descent

print(f"The float 32 tensor is: {float_32_tensor} with a shape of: {float_32_tensor.shape} a datatype of:{float_32_tensor.dtype} and is on the device: {float_32_tensor.device}")

#Common issues
#1. one of tensors is 16 bit and others is 32, PyTorch often likes its tensors in the same format
#2. One of ur tensors is on the GPU and others is on the CPU, PyTorch likes the calculations to be on the same device

#For now let us also create a float 16 tensor
float_16_tensor = torch.tensor([1.1, 2.2, 3.3], #the numbers that will print will be different than 1.1, 2.2, 3.3 because of the precision for half's
                            dtype=torch.half,
                            device=None,
                            requires_grad=False)

print(f"The float 16 tensor is: {float_16_tensor} with a shape of: {float_16_tensor.shape} a datatype of: {float_16_tensor.dtype} and is on the device: {float_16_tensor.device}")

The float 32 tensor is: tensor([3., 6., 9.]) with a shape of: torch.Size([3]) a datatype of:torch.float32 and is on the device: cpu
The float 16 tensor is: tensor([1.0996, 2.1992, 3.3008], dtype=torch.float16) with a shape of: torch.Size([3]) a datatype of: torch.float16 and is on the device: cpu


# Getting Info from Tensors
- Most commonly, we want to get shape, dtype, and device
- Let's create a random tensor of size (3,2,2,1) and get these attributes

In [ ]:
taka_tensor = torch.rand(3,2,2,1) #think of a 3 sets of (pairs of (2x1 matrices)), which has ndim of 4
print(f"The random tensor is: {taka_tensor}")
print(f"The shape is {taka_tensor.shape}, the datatype is {taka_tensor.dtype}, and the device is {taka_tensor.device}")

The random tensor is: tensor([[[[0.9209],
          [0.6574]],

         [[0.2257],
          [0.4435]]],


        [[[0.9077],
          [0.8990]],

         [[0.1465],
          [0.4703]]],


        [[[0.9526],
          [0.2359]],

         [[0.6053],
          [0.6296]]]])
The shape is torch.Size([3, 2, 2, 1]), the datatype is torch.float32, and the device is cpu


# Manipulating Tensors
- In DL, data (images, text, video, audio, protein structures) gets represented as tensors
- Model learns by investigating tensors, operations, and getting representation of patterns in the input data
## Basic Operations
- We will start with addition subtraction & multiplication
- We will use +=, *=, etc. so that we re-assign the tensor
- **Note**: If we just use * or =, the original tensor will stay the same!

In [15]:
#Create a tensor of values & do an operation
tensor = torch.tensor([1,2,3])

tensor += 10
print(f"Addition:The original tensor was [1,2,3] and the new tensor is: {tensor}")

mult_tensor = torch.tensor([2,4,6,8])
mult_tensor *= 10
print(f"Multiplication: The original tensor was [2,4,6,8] and the new tensor is: {mult_tensor}")

#Can obviously do the same with subtraction and division

Addition:The original tensor was [1,2,3] and the new tensor is: tensor([11, 12, 13])
Multiplication: The original tensor was [2,4,6,8] and the new tensor is: tensor([20, 40, 60, 80])


### Built in Tensor Operations 

In [16]:
tensor = torch.tensor([1,2,3,4,5])
print(f"The original tensor is: {tensor}")
torch.mul(tensor, 10) #Can use mul or multiply, same function
#The above function did NOT change the actual tensor, we need to re-assign it to do that as previously

#Another way to do this is to just use the * operator
tensor * 10

The original tensor is: tensor([1, 2, 3, 4, 5])


tensor([10, 20, 30, 40, 50])

## Matrix Multiplication *torch.matmul()* or **@**
- 1 of the most common operations in ML DL 
- the matmul() operator can be shortened to @
    - Using @ on 1D tensors just computes the dot product, which returns a scalar (0D Tensor)
    - Using @ on 2D Tensors requires the rules below
- Rules
    1. Inner dimensions must match: (3,2)@(2,3)
    2. Resulting matrix has shape of outer dimensions, above gives a (3,3)

### Example below: We work with 1D tensors (vectors), so @ yields dot product! This won't apply with ndim>2

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
print(f"The first tensor is: {tensor1} \n and the second tensor is: {tensor2}")

matrix_multiplication = tensor1 @ tensor2
print(f"Matrix Multiplication: {matrix_multiplication}")

The first tensor is: tensor([1, 2, 3]) 
 and the second tensor is: tensor([4, 5, 6])
Matrix Multiplication: 32


### Matrix Mul by Hand via For loop

In [17]:
tensor = torch.tensor([1,2,3]) 
value=0
print(f"The original tensor is: {tensor} with shape {tensor.shape}. The len(tensor) length function returns {len(tensor)}")
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

The original tensor is: tensor([1, 2, 3]) with shape torch.Size([3]). The len(tensor) length function returns 3


tensor(14)

# Shape Errors
- One of the most common errors resulting from matrix multiplication
## Using Transpose

In [21]:
tensor_A = torch.tensor([[1,2], #ndim=2, shape=torch.size([3,2])
                        [3,4],
                        [5,6]]
                        )
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
#tensor_A @ tensor_B will throw an error because the inner dimensions do not match; cannot do a 3x2 @ 3x2

#2 ways to transpose
method1 = torch.transpose(tensor_A, 0,1) #input, and dimensions we will swap
method2 = tensor_A.T #T is short for transpose

print(f"Tensor A with shape {tensor_A.shape} and Tensor B with shape {tensor_B.shape}")
print(f"Tensor A transpose is {method2} and has shape {method2.shape}")
print(f"Multiplication of A^T @ B is {method2 @ tensor_B}")

Tensor A with shape torch.Size([3, 2]) and Tensor B with shape torch.Size([3, 2])
Tensor A transpose is tensor([[1, 3, 5],
        [2, 4, 6]]) and has shape torch.Size([2, 3])
Multiplication of A^T @ B is tensor([[ 89,  98],
        [116, 128]])


## Linear Modules
- The *torch.nn.linear* module is known as the **feed-forward layer / fully connected layer**, implemented by the equation $$y=x*A^T+b$$
- It implements a matrix multiplication between input *x* and weight matrix *W*
    - $x$ is the input to the layer (DL is a stack of layers like torch.nn.Linear() and other on top of each other)
    - $W$ is weights matrix created by the layer, randomly initialized, and we ALWAYS transpose it for matmul @
    - $b$ is the bias term used to slightly offset the weights and inputs
    - $y$ is the output, a manipulation of the input in hopes of discovering patterns in it
- The torch.nn.Linear module is a linear function and can be used to draw a straight line

In [ ]:
#Since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42) #this way we have consistency every time we initialize the random weights

tensorA = torch.tensor([[1,2], #ndim=2, shape=torch.size([3,2])
                        [3,4],
                        [5,6]]
                        )

#We now use matmul
linear = torch.nn.Linear(in_features=3, #matches inner dimension of input
                        out_features=6) #decribes outer value

x=tensorA.float().T #Our input tensor from earlier is a 3x2 matrix, and also we must make it into a float for torch.nn.Linear()
output = linear(x) #Our output outer value will have 6 as its outer dimension, so we must make the inner dimension match with 2, so W is a 2x6
print(f"Input Tensor: {x} with a shape of: {x.shape}")
print(f"Output Tensor: {output} with a shape of: {output.shape}")


Input Tensor: tensor([[1., 3., 5.],
        [2., 4., 6.]]) with a shape of: torch.Size([2, 3])
Output Tensor: tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>) with a shape of: torch.Size([2, 6])


## Aggregation: min, max, mean, sum 
Now that we have manipulated tensors, lets aggregate (going from more values to less values)

In [19]:
x = torch.arange(0,101,10)
print(f"The original tensor is: {x}")

print(f"Min: {x.min()}, Max: {x.max()}, Mean: {x.type(torch.float32).mean()}, Sum: {x.sum()}") 
#Mean MUST be a float, so we must convert x to a float for that argument

#Alternative commands, but this will give you tensor outputs rather than normal floats/ints
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

The original tensor is: tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Min: 0, Max: 100, Mean: 50.0, Sum: 550


(tensor(100), tensor(0), tensor(50.), tensor(550))

### Positional Min/Max
- You can also find the index of a tensor where the max or min occurs with *torch.argmax()* and *torch.argmin()* respectively
    - Remember, arg means argument here
- This is helpful when we just want the position where the highest or lowest val is and not the actual value itself
    - This will be used later when using the **softmax** activation function

In [24]:
pos = torch.rand(10) #Remember with torch.rand, we aren't initializing the values, we are just creating a random tensor and each argument represents a dimension
print(pos) #this example has a value of 10 in the 1st dimension, so we get a ndim=1 tensor (vector) with 10 nums

print(f"The position of the min occuring value is {pos.argmin()} and the max is at {pos.argmax()}")

tensor([0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104,
        0.9464])
The position of the min occuring value is 0 and the max is at 9


## Datatypes and Tensor Precision
- Different datatypes can be confusing to begin with.
- the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value
    - with a lower amount of storage, this generally results in faster computation and a smaller overall model
- Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts
### Type Casting a Float-32 Tensor

In [29]:
# Create a tensor and check its datatype
tensor = torch.arange(10.1, 100.1, 10.1) #Default is float32
print(tensor, tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16) #changing a dtype is called type casting
print(tensor_float16)

# Create a float16 tensor
tensor_int8 = tensor.type(torch.int8) #This will change the dtype to integer 8
print(tensor_int8)

tensor([10.1000, 20.2000, 30.3000, 40.4000, 50.5000, 60.6000, 70.7000, 80.8000,
        90.9000]) torch.float32
tensor([10.1016, 20.2031, 30.2969, 40.4062, 50.5000, 60.5938, 70.6875, 80.8125,
        90.8750], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


## Reshaping, Stacking, Squeeze/Unsqueezing
- Often want to reshape or change the dimensions of your tensors without actually changing the values inside them
    - Much more complex version of transposing
- ```torch.reshape(input, shape)``` Reshapes input to shape if compatible, can also use ```torch.Tensor.reshape()```
- ```Tensor.view(shape)``` Returns a view of the original tensor in a different shape but shares the same data as the original tensor
- ```torch.stack(tensors, dim=0)``` Concatenates a sequence of tensors along a new dimensions (dim), all tensors must be the same size
- ```torch.squeeze(input)``` Squeezes input to remove all the dimensions with value 1
- ```torch.unsqueeze(input, dim)``` Returns input with a dimension value of 1 added at dim
- ```torch.permute(input, dims)``` Returns a view of the original input with its dimensions permuted (rearranged) to dims

We do these things because NNs are all about manipulating tensors in some way. These methods ensure we avoid matmul errors, and also mixing the right elements in the tensors

In [32]:
x = torch.arange(1,8)
print(f"Our original tensor is {x} with shape {x.shape}")

#Adding an extra dimension with torch.reshape()
x_reshaped = x.reshape(1,7) #Here the (1,7) is the desired shape
print(f"\nUsing .reshape we now have {x_reshaped} with shape {x_reshaped.shape}")
# Notice we keep the same number of elements so this is basically adding an extra dimension, exressing the vector as a row vector



#We can also change the view with torch.view()
#Again, this keeps data the same as original but changes the view, so it's basically the same as reshape
z = x.view(1,7) 
print(f"\nUsing .view() we now have {z} with shape {z.shape} while x is still {x} with shape {x.shape}")
#Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor
#So changing the view changes the original tensor too

z[:, 0] = 5 #This will change the first element of the tensor
print(f"\nChanging the view of z by replacing 0th element with 5: {z} changes the original tensor x: {x}")



#If we want to STACK our new tensor on top of itself 5 times, we could do that with torch.stack()
#The dimension argument in stack is the dimension we want to stack along
#So if we want to stack along first dimension, we use 0 (stack rows), whereas 2nd dimension, we use dim=1 and it stack columns
x_stacked = torch.stack([x,x,x,x], dim=0)
print(f"\nUsing torch.stack([x,x,x,x], dim=0) (rows, 1st dimension) we now have {x_stacked} with shape {x_stacked.shape}")
x_stacked2 = torch.stack([x,x,x,x], dim=1)
print(f"Using torch.stack() with dim=1 (columns, 2nd dimension) we now have {x_stacked2} with shape {x_stacked2.shape}")



#If we want to remove all single dimensions from a tensor, we can use torch.squeeze()
#REMEMBER: Think of this as squeezing the tensor to only have dimensions over 1
print(f"\nPrevious tensor before squeezing is: {x_reshaped} with shape {x_reshaped.shape}")
#Removing the extra dimension 
x_squeezed = x_reshaped.squeeze()
print(f"The new tensor after squeezing (removing a extra dimension of 1) is: {x_squeezed} with shape {x_squeezed.shape}")

#To reverse the removal of the 1-dimension, we can add a dimensions value of 1 at a specific index
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"The new tensor after unsqueezing (adding a extra dimension of 1) is: {x_unsqueezed} with shape {x_unsqueezed.shape}")


#Finally, we can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims
x_original = torch.rand(224,224,3) #remember with the rand initialization, the 0th dimension is the outermost (number of sets of 224x3 matrices)
#Now we will permute to rearrange axes order
x_permuted = x_original.permute(2,0,1) #JUST LOOK AT ORIGINAL TENSOR AND REARRANGE BASED ON THE NUMBER (2nd of OG, 0th of OG, 1st of OG), where OG was (0,1,2)
print(f"\nThe original tensor is: {x_original} with shape {x_original.shape}")
print(f"The permuted tensor is: {x_permuted} with shape {x_permuted.shape}")

Our original tensor is tensor([1, 2, 3, 4, 5, 6, 7]) with shape torch.Size([7])

Using .reshape we now have tensor([[1, 2, 3, 4, 5, 6, 7]]) with shape torch.Size([1, 7])

Using .view() we now have tensor([[1, 2, 3, 4, 5, 6, 7]]) with shape torch.Size([1, 7]) while x is still tensor([1, 2, 3, 4, 5, 6, 7]) with shape torch.Size([7])

Changing the view of z by replacing 0th element with 5: tensor([[5, 2, 3, 4, 5, 6, 7]]) changes the original tensor x: tensor([5, 2, 3, 4, 5, 6, 7])

Using torch.stack([x,x,x,x], dim=0) (rows, 1st dimension) we now have tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]]) with shape torch.Size([4, 7])
Using torch.stack() with dim=1 (columns, 2nd dimension) we now have tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]]) with shape torch.Size([7, 4])

Previous tensor before squeezing is: 

# Indexing (selecting data from tensors)
- Sometimes, you'll want to select specific data from tensor (for example, only the first column or second row)
- This is very similar to indexing on Python lists and NumPy arrays

In [35]:
x = torch.arange(1,10) #gives me a 1D tensor (vector 1 thru 9), so 9 elements
print(x)
y = x.reshape(1,3,3) #This will work because 3x3 matrix contains 9 elements abd 
print(y, y.shape) 

#Indexing Values goes from OUTER TO INNER dimension (check out the square brackets)
print(f"\nFirst square bracket y[0]: {y[0]}") #This will return the full 3x3 matrix but squeezed; it is the first element of the ENTIRE tensor
print(f"Second square bracket y[0][0]: {y[0][0]}") #This will give the first element of above, so the first row of the matrix (row vector)
print(f"Third square bracket y[0][0][0]: {y[0][0][0]}") #This will give the first element of the row vector


#You can also use : to specify "all vals in this dimension" and the use a comma to add another dimension
print(f"\nAll Values of 0th dim, but only only 0 index of 1st dim y[:,0]: {y[:,0]}") #Gets all values of 0th dimension (so keeps the outermost dimension) and only the 0th element of the 1st dimension

#Get all values of the 0th & 1st dimensions, but only index 1 of 2nd dimension
print(f"\nAll values of 0th and 1st dim, but only index 1 of 2nd dim y[:,:,1]: {y[:,:,1]}")

print(f"\nAll values of the 0th dimension but the 1 index values of the 1st & 2nd dims y[:,1,1]: {y[:,1,1]}")
#
print(f"\nGet index 0 of the 0th & 1st dim and all values of 2nd dimensions y[0,0,:]: {y[0,0,:]}")

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])

First square bracket y[0]: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket y[0][0]: tensor([1, 2, 3])
Third square bracket y[0][0][0]: 1

All Values of 0th dim, but only only 0 index of 1st dim y[:,0]: tensor([[1, 2, 3]])

All values of 0th and 1st dim, but only index 1 of 2nd dim y[:,:,1]: tensor([[2, 5, 8]])

All values of the 0th dimension but the 1 index values of the 1st & 2nd dims y[:,1,1]: tensor([5])

Get index 0 of the 0th & 1st dim and all values of 2nd dimensions y[0,0,:]: tensor([1, 2, 3])
