# PyTorch Tensors & Numpy
- Since NumPy is a popular python numerical computing library, PyTorch has funcitonality to interact w/ it nicely
- The 2 main methods you'll want to use for NumPy to PyTorch and back again are:
    - ```torch.from_numpy(ndarray)```: NumPy array to PyTorch tensor
    - ```torch.Tensor.numpy```: PyTorch tensor to NumPy array

In [13]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

- By default, NumPy array are cfreated with a datatype of float 64 and if you convert to a tensor, it'll keep the same datatype as above
- But remember, many torch calcs go with float 32. With that in mind, you can use the following function to convert numpy float64 -> tensor.float64 -> torch.float32: ```tensor=torch.from_numpy(array).type(torch.float32)```
- Because we reasigned tensor above, if you change the tensor, the array stays the SAME

In [ ]:
#Change the array, keep the tensor the same
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [15]:
#Go from tensor to Numpy arrya
tensor = torch.ones(5)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)
- Randomness plays a hgue part, in NN's, we start with random numbers and try to improve them through tensor operations
- Sometimes we want less randomness so we can perform repeatable experiments, like can we get the same results on two different computers with the same code?

Let us begin by creating 2 random tensors, since they are random, you expect them to be diff right?

In [17]:
import torch

#Creating 2 random tensors
random_tensorA = torch.rand(3,4) #which has shape torch.size(3,4), and has 2 dimensions
random_tensorB = torch.rand(3,4)

print(f"Random Tensor A is: {random_tensorA} \n Random Tensor B is: {random_tensorB}")
print(f"Does Random tensor a = tensor B anywhere?")
random_tensorA == random_tensorB

Random Tensor A is: tensor([[0.5447, 0.4065, 0.4464, 0.2232],
        [0.9002, 0.0507, 0.0361, 0.0237],
        [0.1237, 0.2245, 0.8873, 0.3452]]) 
 Random Tensor B is: tensor([[0.1802, 0.2826, 0.4492, 0.4714],
        [0.3024, 0.5666, 0.8403, 0.7207],
        [0.0235, 0.6174, 0.8729, 0.8232]])
Does Random tensor a = tensor B anywhere?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

## Random Seeds
- This allows us to create 2 random tensors with the same values

In [ ]:
import torch
import random

#Setting the random seed, different seeds will give different random tensors because the random number generator is initialized differently
RANDOM_SEED=42 #The reason re capitalize is because it's a constant
torch.manual_seed(seed=RANDOM_SEED) #manual seed is the seed we set manually
random_tensorC = torch.rand(3,4)

#We need to reset the seed every time a new rand() is called
#Without this, tensorD would be different to tensorC
torch.random.manual_seed(seed=RANDOM_SEED) #Try commenting this line out and see what happens
random_tensorD = torch.rand(3,4)

print(f"Random Tensor C is: {random_tensorC} \n Random Tensor D is: {random_tensorD}")
print(f"Does Tensor C = D anywhere?")
random_tensorC == random_tensorD



Random Tensor C is: tensor([[0.3189, 0.6136, 0.4418, 0.2580],
        [0.2724, 0.6261, 0.4410, 0.3653],
        [0.3535, 0.5971, 0.3572, 0.4807]]) 
 Random Tensor D is: tensor([[0.3189, 0.6136, 0.4418, 0.2580],
        [0.2724, 0.6261, 0.4410, 0.3653],
        [0.3535, 0.5971, 0.3572, 0.4807]])
Does Tensor C = D anywhere?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running Tensor on GPUs (and making faster computations)
- To check if you have access to a Nvidia GPU, you can run ```nvidia-smi``` 
- Once you have a GPU, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors)

In [28]:
#Checking for a GPU
import torch
torch.cuda.is_available()

True

- If this returned true, you have access
- If you want your code to run whether there is a GPU available or not:

In [30]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [31]:
#Find the number of available devices
torch.cuda.device_count()

1

# Putting Tensors (and models) on the GPU
- You can put tensors on a specific device by calling to(device) on them, where device is the target device you want the tensor or model to go to

In [33]:
#Create a tensor (defaults on CPU)
tensor = torch.tensor([1,2,3])
#Tensor location
print(tensor, tensor.device)

#Moving the tensor to GPU 
tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device

tensor([1, 2, 3]) cpu


(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
#Moving the tensors back to the CPU