In [8]:
# Create a random tensor with shape (7,7)
import torch
tensor = torch.rand(7,7)
print(tensor)

#performing matrix multiplication on the tensor with another random tensor of shape (1,7)
tensor2 = torch.rand(1,7)
product = tensor @ tensor2.T
print(product)

tensor([[0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047, 0.1100],
        [0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
        [0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967, 0.1957],
        [0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186],
        [0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748],
        [0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743, 0.4743],
        [0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179, 0.9736]])
tensor([[2.1422],
        [1.8840],
        [1.3052],
        [2.5827],
        [1.6046],
        [1.1300],
        [2.7294]])


In [12]:
# Setting the random seed to 0 and do the same thing from above again
torch.manual_seed(0)
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
product = tensor1 @ tensor2.T
print(product)

torch.cuda.is_available()

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


True

In [17]:
#Setting the GPU equivalent for random seed
torch.cuda.manual_seed(1234)
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_gpu1 = torch.rand(2,3)
tensor_gpu2 = torch.rand(2,3)
g1 = tensor_gpu1.to(device)
g2 = tensor_gpu2.to(device)

prod = g1 @ g2.T
print(prod, prod.shape)

tensor([[0.4223, 0.4460],
        [0.5227, 0.5522]], device='cuda:0') torch.Size([2, 2])


In [19]:
#Finding max and min of prod
print(prod.max(), prod.min(), prod.argmax(), prod.argmin())

tensor(0.5522, device='cuda:0') tensor(0.4223, device='cuda:0') tensor(3, device='cuda:0') tensor(0, device='cuda:0')


In [ ]:
#Make a random tensor with shape (1,1,1,10) and then creatre a new tensor with all the 1 dimension to be left with a tensor of shape (10). Set the seed to 7 when creating it

torch.manual_seed(7)

tensor = torch.rand(1,1,1,10)
print(tensor, tensor.shape)
new_tensor = tensor.squeeze()
print(new_tensor, new_tensor.shape)

#Create a tensor with shape (100,100) and then create a new tensor with all the 100 dimension to be left with a tensor of shape (100). Set the seed to 7 when creating it

torch.manual_seed(7)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
